### ISSUE TITLE
libliri tries to find files that are not installed yet, because they belong to libliri

### ISSUE THREAD

**Issue by n3rdopolis** [lirios/libliri#1]
HI

It seems libliri tries to find <LiriNotifications/Notification> before it is installed, and errors out
If I install the failed built, and try again, it works, because <LiriNotifications/Notification> is installed

Thanks

This is what I am building with (I intentionally split the configure part and the compile part, so that dependency resolution is in a separate log)...
```
qbs setup-toolchains --type gcc /usr/bin/g++ gcc
qbs setup-qt /opt/bin/qmake qt5
qbs config profiles.qt5.baseProfile gcc
qbs resolve profile:qt5
qbs build -j $BUILD_CPU_COUNT --no-install profile:qt5 qbs.installRoot:$INSTALLDIR qbs.installPrefix:/ qbs.buildVariant:release
```
This is the output I get
```
libliri: creating module header LiriModels
libliri: moc qobjectlistmodel.h
libliri: moc application_adaptor.h
libliri: moc dbusservice.h
libliri: ERROR: /usr/bin/g++ -O2 -Wall -Wextra -m64 -pipe -fexceptions -fvisibility=default -fPIC -DNDEBUG '-DLIBLIRI_VERSION="0.9.0"' -DQT_CORE_LIB -DQT_NO_DEBUG -DQT_DBUS_LIB -DQT_GUI_LIB -I/srcbuild/libliri/default/include -I/srcbuild/libliri/default/include/LiriNotifications -I/srcbuild/libliri/default/include/LiriNotifications/0.9.0 -I/srcbuild/libliri/default/include/LiriNotifications/0.9.0/LiriNotifications -I/srcbuild/libliri/default/include/LiriNotifications/0.9.0/LiriNotifications/private -I/opt/include -I/opt/include/QtCore -I/opt/mkspecs/linux-g++ -I/srcbuild/libliri/default/liri-notify.qt5.bbf93543/qt.headers -I/opt/include/QtCore/5.9.2 -I/opt/include/QtCore/5.9.2/QtCore -I/opt/include/QtDBus -I/opt/include/QtGui -std=c++0x -o /srcbuild/libliri/default/liri-notify.qt5.bbf93543/.obj/3a52ce780950d4d9/main.cpp.o -c /srcbuild/libliri/src/notify/main.cpp
libliri: 
libliri: ERROR: /srcbuild/libliri/src/notify/main.cpp:19:42: fatal error: LiriNotifications/Notification: No such file or directory
libliri:  #include <LiriNotifications/Notification>
libliri:                                           ^
libliri: compilation terminated.
libliri: ERROR: Process failed with exit code 1.
libliri: The following products could not be built for configuration default:
libliri:        liri-notify
libliri:        LiriCore-qbs
libliri:        LiriCore-pkgconfig
libliri:        LiriCore-cmake
libliri:        LiriCore
libliri:        LiriDBusService-qbs
libliri:        LiriDBusService-pkgconfig
libliri:        LiriDBusService-cmake
libliri:        LiriDBusService
libliri:        LiriModels-qbs
libliri:        LiriModels-pkgconfig
libliri:        LiriModels-cmake
libliri:        LiriModels
libliri:        LiriNotifications-qbs
libliri:        LiriNotifications-pkgconfig
libliri:        LiriNotifications-cmake
libliri:        LiriNotifications
libliri:        liricoreplugin
libliri:        lirinotificationsplugin
libliri:        tst_liri_core
```

**Comment by plfiorini** [comment]
Mmm dependencies should handle that.
`liri-notify` has a dependency on `LiriNotifications` and should use include files from the build directory, gcc arguments suggest that the include path is correct.
This probably means that forward headers like `LiriNotifications/Notification` are not generated before building `liri-notify` although `LiriNotifications` has a dependency on the headers.

@n3rdopolis Does this happen all the time or randomly?

**Comment by plfiorini** [comment]
See if adding an explicit dependency to `LiriNotificationsHeaders` to `src/notify/notify.qbs` works:

```qml
Depends { name: "LiriNotificationsHeaders" }
```

**Comment by n3rdopolis** [comment]
That doesn't seem to work unfortunately. It just started happening, not sure what changed, except for 
```
export LIRI_LIBRARY_PREFIX=$INSTALLDIR
export LIRI_INCLUDE_PREFIX=$INSTALLDIR
```
which I tried to unset. Whenever all the libliri files are gone, it happens every time. Unless I try to install the half built libliri, and then try to build it again, it works....
...I also tried to reduce the BUILD_CPU_COUNT to 1

**Comment by n3rdopolis** [comment]
It's odd, and I am going to try again, as it seems it builds fine on 32 bit, but can't find it on 64 bit. I am using the exact revisions too (I build my own Qt), and the 64 bit and 32 bit chroots are built very similar... Same Debian packages, same configs...

**Comment by n3rdopolis** [comment]
I tried again, rebuilt 32 and 64 bit. they both have the same revisions of everything, and 64 bit libliri had the header issue, and 32 bit did not

Are there any more logs I could give you, I tried to run the compile command with the -v flag, and qbs did not like it...

**Comment by n3rdopolis** [comment]
This still occurs, oddly only on my 64 bit chroot, and not my 32 bit one, even though the same scripts build them

This is libliri's successful build on 32 bit
```
Restoring build graph from disk                                                                                                                                                                                                                                                
Resolving project for configuration default                                                                                                                                                                                                                                    
Building for configuration default                                                                                                                                                                                                                                             
Creating lirimodelsversion.h                                                                                                                                                                                                                                                   
moc qobjectlistmodel.h                                                                                                                                                                                                                                                         
Creating liricoreversion.h                                                                                                                                                                                                                                                     
moc kformat.h                                                                                                                                                                                                                                                                  
moc desktopfileaction.h                                                                                                                                                                                                                                                        
moc desktopfile.h                                                                                                                                                                                                                                                              
moc tst_qobjectlistmodel.cpp                                                                                                                                                                                                                                                   
Creating lirinotificationsversion.h                                                                                                                                                                                                                                            
syncing qobjectlistmodel.h                                                                                                                                                                                                                                                     
syncing qquicklist.h                                                                                                                                                                                                                                                           
syncing lirimodelsversion.h                                                                                                                                                                                                                                                    
syncing lirimodelsglobal.h                                                                                                                                                                                                                                                     
syncing liricoreglobal.h                                                                                                                                                                                                                                                       
syncing desktopfile.h                                                                                                                                                                                                                                                          
creating module header LiriModels                                                                                                                                                                                                                                              
syncing kformat.h                                                                                                                                                                                                                                                              
syncing desktopfileaction.h                                                                                                                                                                                                                                                    
syncing liricoreversion.h                                                                                                                                                                                                                                                      
syncing kformatprivate_p.h                                                                                                                                                                                                                                                     
syncing lirinotificationsglobal.h                                                                                                                                                                                                                                              
syncing notification_p.h                                                                                                                                                                                                                                                       
creating module header LiriCore                                                                                                                                                                                                                                                
syncing notification.h                                                                                                                                                                                                                                                         
syncing lirinotificationsversion.h
qdbusxml2cpp org.freedesktop.Notifications.xml -> notifications_interface.h
qdbusxml2cpp org.freedesktop.Notifications.xml -> notifications_adaptor.h
creating module header LiriNotifications
moc plugin.cpp
qdbusxml2cpp org.freedesktop.Notifications.xml -> notifications_interface.cpp
qdbusxml2cpp org.freedesktop.Notifications.xml -> notifications_adaptor.cpp
moc notifications_interface.h
moc notification.h
moc notifications_adaptor.h
moc notifications.h
compiling moc_desktopfile.cpp
compiling moc_qobjectlistmodel.cpp
compiling qobjectlistmodel.cpp
compiling moc_desktopfileaction.cpp
compiling desktopfileaction.cpp
compiling desktopfile.cpp
compiling kformat.cpp
compiling kformatprivate.cpp
compiling tst_qobjectlistmodel.cpp
compiling moc_notification.cpp
compiling notifications_interface.cpp
compiling moc_notifications_interface.cpp
compiling notification.cpp
moc notificationsdaemon.h
moc plugin.cpp
moc formatter.h
compiling moc_notifications.cpp
compiling notifications.cpp
linking libLiriModels.so.0.0.0
linking libLiriCore.so.0.0.0
creating symbolic link 'libLiriModels.so'
creating symbolic link 'libLiriModels.so.0'
creating symbolic link 'libLiriModels.so.0.0'
compiling notifications_adaptor.cpp
creating symbolic link 'libLiriCore.so'
creating symbolic link 'libLiriCore.so.0'
creating symbolic link 'libLiriCore.so.0.0'
compiling plugin.cpp
compiling notificationsimageprovider.cpp
compiling notificationsimage.cpp
linking tst_liri_core
compiling notificationsdaemon.cpp
compiling moc_notificationsdaemon.cpp
compiling moc_notifications_adaptor.cpp
generate qbs module LiriModels.qbs
generating LiriModels.pc
generating LiriModelsConfig.cmake
generating LiriModelsConfigVersion.cmake
compiling moc_formatter.cpp
compiling plugin.cpp
/usr/bin/g++ -O2 -Wall -Wextra -m32 -pipe -fexceptions -fvisibility=hidden -fvisibility-inlines-hidden -fPIC -DNDEBUG -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_TO_ASCII '-DLIBLIRI_VERSION="0.9.0"' -DQT_CORE_LIB -DQT_NO_DEBUG -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_QML_LIB -DQT_QUICK_LIB -I/srcbuild/libliri/src/imports/notifications -I/srcbuild/libliri/default/include -I/srcbuild/libliri/default/include/LiriNotifications -I/srcbuild/libliri/default/include/LiriNotifications/0.9.0 -I/srcbuild/libliri/default/include/LiriNotifications/0.9.0/LiriNotifications -I/srcbuild/libliri/default/include/LiriNotifications/0.9.0/LiriNotifications/private -I/opt/include -I/opt/include/QtCore -I/opt/mkspecs/linux-g++ -I/srcbuild/libliri/default/lirinotificationsplugin.qt5.a908fb29/qt.headers -I/opt/include/QtCore/5.9.2 -I/opt/include/QtCore/5.9.2/QtCore -I/opt/include/QtDBus -I/opt/include/QtGui -I/opt/include/QtNetwork -I/opt/include/QtQml -I/opt/include/QtQuick -std=c++0x -o /srcbuild/libliri/default/lirinotificationsplugin.qt5.a908fb29/.obj/3a52ce780950d4d9/notifications_adaptor.cpp.o -c /srcbuild/libliri/default/lirinotificationsplugin.qt5.a908fb29/notifications_adaptor.cpp

/srcbuild/libliri/default/lirinotificationsplugin.qt5.a908fb29/notifications_adaptor.cpp: In member function ‘QString NotificationsAdaptor::GetServerInformation(QString&, QString&, QString&)’:
/srcbuild/libliri/default/lirinotificationsplugin.qt5.a908fb29/notifications_adaptor.cpp:54:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
/srcbuild/libliri/default/lirinotificationsplugin.qt5.a908fb29/notifications_adaptor.cpp:50:61: warning: unused parameter ‘vendor’ [-Wunused-parameter]
 QString NotificationsAdaptor::GetServerInformation(QString &vendor, QString &version, QString &spec_version)
                                                             ^~~~~~
/srcbuild/libliri/default/lirinotificationsplugin.qt5.a908fb29/notifications_adaptor.cpp:50:78: warning: unused parameter ‘version’ [-Wunused-parameter]
 QString NotificationsAdaptor::GetServerInformation(QString &vendor, QString &version, QString &spec_version)
                                                                              ^~~~~~~
/srcbuild/libliri/default/lirinotificationsplugin.qt5.a908fb29/notifications_adaptor.cpp:50:96: warning: unused parameter ‘spec_version’ [-Wunused-parameter]
 QString NotificationsAdaptor::GetServerInformation(QString &vendor, QString &version, QString &spec_version)
                                                                                                ^~~~~~~~~~~~
compiling formatter.cpp
Creating liridbusserviceversion.h
syncing liridbusserviceversion.h
syncing liridbusserviceglobal.h
syncing dbusservice.h
creating module header LiriDBusService
qdbusxml2cpp org.freedesktop.Application.xml -> application_adaptor.h
qdbusxml2cpp org.freedesktop.Application.xml -> application_adaptor.cpp
linking libLiriNotifications.so.0.0.0
moc application_adaptor.h
moc dbusservice.h
compiling application_adaptor.cpp
creating symbolic link 'libLiriNotifications.so'
creating symbolic link 'libLiriNotifications.so.0'
creating symbolic link 'libLiriNotifications.so.0.0'
generate qbs module LiriNotifications.qbs
generating LiriNotificationsConfigVersion.cmake
generating LiriNotificationsConfig.cmake
generating LiriNotifications.pc
compiling moc_dbusservice.cpp
compiling moc_application_adaptor.cpp
compiling dbusservice.cpp
compiling main.cpp
generate qbs module LiriCore.qbs
generating LiriCore.pc
generating LiriCoreConfig.cmake
generating LiriCoreConfigVersion.cmake
linking liri-notify
linking libliricoreplugin.so
linking liblirinotificationsplugin.so
linking libLiriDBusService.so.0.0.0
creating symbolic link 'libLiriDBusService.so'
creating symbolic link 'libLiriDBusService.so.0'
creating symbolic link 'libLiriDBusService.so.0.0'
generate qbs module LiriDBusService.qbs
generating LiriDBusService.pc
generating LiriDBusServiceConfig.cmake
generating LiriDBusServiceConfigVersion.cmake
Build done for configuration default.
PackageCompileSource finished in 13 seconds
```


This is the 64 bit version that fails
```
Restoring build graph from disk
Resolving project for configuration default
Building for configuration default
Creating lirinotificationsversion.h
qdbusxml2cpp org.freedesktop.Notifications.xml -> notifications_interface.h
compiling main.cpp
Creating liricoreversion.h
moc desktopfile.h
moc desktopfileaction.h
moc kformat.h
Creating liridbusserviceversion.h
qdbusxml2cpp org.freedesktop.Notifications.xml -> notifications_interface.cpp
syncing notification_p.h
syncing notification.h
syncing lirinotificationsglobal.h
syncing lirinotificationsversion.h
moc notifications_interface.h
moc notification.h
syncing liricoreversion.h
creating module header LiriNotifications
syncing kformat.h
syncing desktopfile.h
syncing desktopfileaction.h
syncing kformatprivate_p.h
syncing liricoreglobal.h
syncing liridbusserviceversion.h
creating module header LiriCore
syncing dbusservice.h
syncing liridbusserviceglobal.h
qdbusxml2cpp org.freedesktop.Application.xml -> application_adaptor.h
creating module header LiriDBusService
Creating lirimodelsversion.h
syncing qobjectlistmodel.h
qdbusxml2cpp org.freedesktop.Application.xml -> application_adaptor.cpp
syncing lirimodelsglobal.h
syncing lirimodelsversion.h
syncing qquicklist.h
creating module header LiriModels
moc qobjectlistmodel.h
moc application_adaptor.h
moc dbusservice.h
ERROR: /usr/bin/g++ -O2 -Wall -Wextra -m64 -pipe -fexceptions -fvisibility=default -fPIC -DNDEBUG '-DLIBLIRI_VERSION="0.9.0"' -DQT_CORE_LIB -DQT_NO_DEBUG -DQT_DBUS_LIB -DQT_GUI_LIB -I/srcbuild/libliri/default/include -I/srcbuild/libliri/default/include/LiriNotifications -I/srcbuild/libliri/default/include/LiriNotifications/0.9.0 -I/srcbuild/libliri/default/include/LiriNotifications/0.9.0/LiriNotifications -I/srcbuild/libliri/default/include/LiriNotifications/0.9.0/LiriNotifications/private -I/opt/include -I/opt/include/QtCore -I/opt/mkspecs/linux-g++ -I/srcbuild/libliri/default/liri-notify.qt5.bbf93543/qt.headers -I/opt/include/QtCore/5.9.2 -I/opt/include/QtCore/5.9.2/QtCore -I/opt/include/QtDBus -I/opt/include/QtGui -std=c++0x -o /srcbuild/libliri/default/liri-notify.qt5.bbf93543/.obj/3a52ce780950d4d9/main.cpp.o -c /srcbuild/libliri/src/notify/main.cpp

ERROR: /srcbuild/libliri/src/notify/main.cpp:19:42: fatal error: LiriNotifications/Notification: No such file or directory
 #include <LiriNotifications/Notification>
                                          ^
compilation terminated.
ERROR: Process failed with exit code 1.
The following products could not be built for configuration default:
        liri-notify
        LiriCore-qbs
        LiriCore-pkgconfig
        LiriCore-cmake
        LiriCore
        LiriDBusService-qbs
        LiriDBusService-pkgconfig
        LiriDBusService-cmake
        LiriDBusService
        LiriModels-qbs
        LiriModels-pkgconfig
        LiriModels-cmake
        LiriModels
        LiriNotifications-qbs
        LiriNotifications-pkgconfig
        LiriNotifications-cmake
        LiriNotifications
        liricoreplugin
        lirinotificationsplugin
        tst_liri_core
PackageCompileSource finished in 1 seconds

```

It seems it gets built in a different order, if I compare the logs with kompare. not sure why

**Comment by plfiorini** [comment]
Yesterday I have updated my Arch laptop and tried to build libliri-git from AUR only to reproduce this problem. If I build from the desktop that has a slightly older Arch and qbs 1.8.0 instead of 1.8.1 I cannot seem to reproduce the issue. Can't reproduce either when building the whole Liri sources from QtCreator.

This make me believe there is something in my qbs code that no longer work with 1.8.1.

I'm investigating.

**Comment by plfiorini** [comment]
@n3rdopolis Please check if 2e74ebbf5209516b41ae5cf78d7a266ae3862fcf is a valid workaround

**Comment by plfiorini** [comment]
BTW I just updated my desktop and I still can't reproduce it here.

**Comment by n3rdopolis** [comment]
Dang. Seems it doesn't work. Are there any variables that may impact qbs?
Or are there any arguments I can throw at it for more verbose logs?


```
ERROR: /usr/bin/g++ -O2 -Wall -Wextra -m64 -pipe -fexceptions -fvisibility=default -fPIC -DNDEBUG '-DLIBLIRI_VERSION="0.9.0"' -DQT_CORE_LIB -DQT_NO_DEBUG -DQT_DBUS_LIB -DQT_GUI_LIB
 -I/srcbuild/libliri/src -I/srcbuild/libliri/default/include -I/srcbuild/libliri/default/include/LiriNotifications -I/srcbuild/libliri/default/include/LiriNotifications/0.9.0 -I/sr
cbuild/libliri/default/include/LiriNotifications/0.9.0/LiriNotifications -I/srcbuild/libliri/default/include/LiriNotifications/0.9.0/LiriNotifications/private -I/opt/include -I/opt
/include/QtCore -I/opt/mkspecs/linux-g++ -I/srcbuild/libliri/default/liri-notify.qt5.bbf93543/qt.headers -I/opt/include/QtCore/5.9.2 -I/opt/include/QtCore/5.9.2/QtCore -I/opt/inclu
de/QtDBus -I/opt/include/QtGui -std=c++0x -o /srcbuild/libliri/default/liri-notify.qt5.bbf93543/.obj/3a52ce780950d4d9/main.cpp.o -c /srcbuild/libliri/src/notify/main.cpp

ERROR: In file included from /srcbuild/libliri/src/notify/main.cpp:19:0:
/srcbuild/libliri/src/notifications/notification.h:28:55: fatal error: LiriNotifications/lirinotificationsglobal.h: No such file or directory
 #include <LiriNotifications/lirinotificationsglobal.h>
                                                       ^
compilation terminated.
ERROR: Process failed with exit code 1.
```

**Comment by nlgranger** [comment]
@n3rdopolis : FYI I have the exact same message trying to build libliri from AUR on an up to date arch.

**Comment by plfiorini** [comment]
Mmmh perhaps I figured out, in https://github.com/lirios/libliri/blob/develop/libliri.qbs I moved "src/tools.qbs" after "src/imports/imports.qbs" and it builds on my laptop (from AUR).

A patch is ready but first I need to update the CI container otherwise Travis will fail.

**Comment by plfiorini** [comment]
Patch pushed ~1 month ago. Can't reproduce the issue on my laptop anymore.
Closing the issue, please reopen if not fixed for your.
